#-------------------------------
# General Site Settings
title: Anneke reist
logo: logo.jpg # You can add own logo.
description: Annekes Reiseblog

#-------------------------------
# Author Settings
author: Anneke Streit
  name: Annekes Reiseblog
  image: 01.jpg
  say-hello: Hey, willkommen zu meinem <strong>Reiseblog</strong>!
  bio: Hier findet ihr Erzählungen von meinen Erlebnissen beim Work & Travel in Südfrankreich.


#-------------------------------
# Contact links
#twitter: https://twitter.com/ # Add your Twitter handle
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/schwammaccount/ # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
#disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: schwammaccount # Add instagram username



#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
